### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by SalehGladius** [rabbal/Decision#1]
سلام

پروژه بسیار خوبی هست

بنده تلاشمو کردم که روی سیستم خودم اجراش کنم اما متاسفانه اجرا نشد و پیچیدگی های خیلی خاصی داره!

پست آموزشی آقای نصیری در مورد نحوه اجرای پروژه رو هم خوندم اما باز افاقه نکرد

بنده از 
SQLServer 2014
استفاده میکنم و به صورت پیشفرض فایل استریمش فعاله اما در مورد پروژه شما ایراد میگیره!

البته ازین هم بگذریم بعد از بروزرسانی تمامی پکیج ها به آخرین نسخه، در حدود ۲۰۰ خطا در پروژه ظاهر شده که گویا در قسمت مپینگ ورژن قبلی و بعدی پکیچ‌ها با کد همخوانی ندارند.

بر روی سرورهای مجانی هم تست کردم که متاسفانه بازهم اجرا نشد!

خلاصه خواهشمندم اگه براتون مقدوره بر روی یک سرور مجانی پروژه رو اجرایی کنید تا حداقل با بررسی کدها یه نمایی در ذهنمون داشته باشیم از کل کار!

مرسی

**Comment by rabbal** [comment]
سلام.
[مقاله راهنمای راه اندازی پروژه](http://www.dotnettips.info/post/2432/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d9%86%d8%ad%d9%88%d9%87%e2%80%8c%db%8c-%d8%b1%d8%a7%d9%87-%d8%a7%d9%86%d8%af%d8%a7%d8%b2%db%8c-%d9%be%d8%b1%d9%88%da%98%d9%87%e2%80%8c%db%8c-decision)
