### ISSUE TITLE
tight coupling and separation of concerns

### ISSUE THREAD

**Issue by alirezaseif28** [rabbal/Decision#7]
سلام مهندس ربال عزیز.
در یه مقاله در مورد مسائل معماری 
MVC
به این لغات تخصصی رسیدم.
اگه امکانش هست توضیحاتی را ارائه دهید.
the traditional architectures raise fundamental issues like **tight coupling** and **separation of concerns**
مرسی

**Comment by rabbal** [comment]
<div dir="rtl">

[معماری نخیر](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller)، [الگوی معماری](https://en.wikipedia.org/wiki/Architectural_pattern) که لایه Presentation را هدف قرار می‌دهد، صحیح می‌باشد. 

Coupling، به یکی از [اصول GRASP](https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)) در طراحی شیءگرا بنام Low Coupling، اشاره می‎‌کند. برای اطلاعات بیشتر، مطالب مرتبط زیر را پیگیری نمائید:

[اصول طراحی شیء گرا: OO Design Principles - قسمت پنجم](https://www.dotnettips.info/post/2530/%D8%A7%D8%B5%D9%88%D9%84-%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C-%D8%B4%DB%8C%D8%A1-%DA%AF%D8%B1%D8%A7-oo-design-principles-%D9%82%D8%B3%D9%85%D8%AA-%D9%BE%D9%86%D8%AC%D9%85)
[طراحی شیء گرا: OO Design Heuristics - قسمت سوم - Class Coupling and Cohesion](https://www.dotnettips.info/post/2636/%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C-%D8%B4%DB%8C%D8%A1-%DA%AF%D8%B1%D8%A7-oo-design-heuristics-%D9%82%D8%B3%D9%85%D8%AA-%D8%B3%D9%88%D9%85)

اصل [Separation of Concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) نیز به طور خلاصه به فرآیند جداسازی وجوه و موضوعات مختلف یک سیستم از یکدیگر، اشاره دارد . به عبارت ساده تر، تمرکز بر روی فرآیند یا عملکردی از یک سیستم و عدم توجه به کارکرد و جزییات دیگر آن.  
الگوی معماری MVC یک نمونه از این مفهوم می‌باشد. [نمونه دیگر آن ORM ها می‌باشند](https://enterprisecraftsmanship.com/2014/12/06/separation-of-concerns-in-orm/) که هدف جداسازی Domain از Persistence logic را دنبال می‌کنند.

**Comment by alirezaseif28** [comment]
تشکر می کنم.
